name: Build

on:
  push:

jobs:
  ubuntu-build:
    runs-on: ubuntu-22.04
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3.5.3
    
    - name: Install dependencies
      uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: |
          build-essential
          openscad=2021.01*
          calculix-ccx=2.17*
          qtbase5-dev=5.15*
          libcgal-dev=5.4*
          libboost-container-dev=1.74*
          libtet1.5-dev=1.5*
          libgtest-dev=1.11*

    - name: Install linuxdeploy
      uses: miurahr/install-linuxdeploy-action@v1
      with:
        plugins: qt appimage

    - name: Use ccache
      uses: hendrikmuhs/ccache-action@v1

    - name: Compile
      run: |
        qmake
        make -j $(nproc) CC="ccache gcc" CXX="ccache g++" 
    
    - name: Test
      run: test/test

    - name: Build AppImage
      run: |
        linuxdeploy-x86_64.AppImage \
          --appdir AppDir \
          --executable gui/OpenSCAD2CalculiX \
          --icon-file gui/OpenSCAD2CalculiX.png \
          --desktop-file gui/OpenSCAD2CalculiX.desktop \
          --plugin=qt \
          --output=appimage
    
    - uses: actions/upload-artifact@v3
      with:
        name: OpenSCAD2CalculiX-x86_64.AppImage
        path: "*.AppImage"
        if-no-files-found: error
        
