name: Build

on:
  push:

jobs:
  ubuntu-build:
    runs-on: ubuntu-22.04
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3.5.3
    
    - name: Install dependencies
      uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: |
          build-essential
          openscad=2021.01*
          calculix-ccx=2.17*
          qtbase5-dev=5.15*
          libcgal-dev=5.4*
          libboost-dev=1.74*
          libtet1.5-dev=1.5*
          libgtest-dev=1.11*

    - name: Use ccache
      uses: hendrikmuhs/ccache-action@v1

    - name: Compile
      run: |
        qmake
        make -j $(nproc) CC="ccache gcc" CXX="ccache g++" 
    
    - name: Test
      run: test/test
