name: Build

on:
  push:

jobs:
  ubuntu-build:
    runs-on: ubuntu-22.04
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3.5.3
    
    - name: Install dependencies (1)
      uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: |
          openscad=2021.01*
          calculix-ccx=2.17*
          qtbase5-dev=5.15*
          libtet1.5-dev=1.5*
          libgtest-dev=1.11*

    - name: Install dependencies (2)
      # There's some kind of subtle bug where awalsh128/cache-apt-pkgs-action fails
      # to restore the C++ header files properly from the cache. So we have to reinstall
      # the C++ headers every time.
      run: |
        sudo apt-get install \
          libcgal-dev=5.4*

    - name: Install linuxdeploy
      uses: miurahr/install-linuxdeploy-action@v1
      with:
        plugins: qt appimage

    - name: Use ccache
      uses: hendrikmuhs/ccache-action@v1

    - name: Compile
      run: |
        qmake
        make -j $(nproc) CC="ccache gcc" CXX="ccache g++" 
    
    - name: Test
      run: test/test

    - name: Build AppImage
      run: |
        export APPIMAGE_EXTRACT_AND_RUN=1 \
        linuxdeploy-x86_64.AppImage \
          --appdir AppDir \
          --executable gui/OpenSCAD2CalculiX \
          --icon-file gui/OpenSCAD2CalculiX.png \
          --desktop-file gui/OpenSCAD2CalculiX.desktop \
          --plugin=qt \
          --output=appimage \
        mv OpenSCAD2CalculiX*.AppImage OpenSCAD2CalculiX-x86_64.AppImage
          
    - uses: actions/upload-artifact@v3
      with:
        name: OpenSCAD2CalculiX-x86_64.AppImage
        path: OpenSCAD2CalculiX-x86_64.AppImage        
